import marimo

'''
Conceptual Overview:

This notebook gives an interactive visualization of the conditional expectation. The example uses the Lebesgue measure. The Lebesgue measure in lower dimensions (1, 2, 3) coincides exactly with the standard measure of length, area, and volume.

The variable X is defined on the corresponding probability space: P(X \in A) = length(A). When we take the conditional expectation, we project our measure onto the coarsersub-sigma algebra. This corresponds to piecewise constant approximations of X. The finer the sigma algebra (the more intervals) the closer the projection gets to X. n is the size of the partition that generates the sigma algebra $\mathcal{G}$. The smaller n, the coarser the sub-sigma algebra. Conceptually, this can be understood as: by taking the conditional expectation wrt to $\mathcal{G}$, we can only know which set in $\mathcal{G}$ X falls in. The finer the sigma algebra, the smaller the sets are. 

Important takeaways are: 
    - Averaging over the projection results in the average of X (tower property)
    - X may vary a lot over sets that are "invisible" to $\mathcal{G}$, when projecting onto $\mathcal{G}$ / conditioning on $\mathcal{G}$ this variation is averaged out
    - the finer the sigma algebra becomes, the more detail we recover

'''

__generated_with = "0.17.8"
app = marimo.App(width="medium")


@app.cell
def _(mo):
    mo.md(r"""
    # Conditional Expectation  $\sigma$-algebra visualization
    """)
    return


@app.cell
def _():
    import marimo as mo
    import numpy as np
    import matplotlib.pyplot as plt
    return mo, np, plt


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    Let $\Omega = (0,1),\, \mathcal{F} = \mathcal{B}(\Omega), \, P$ the Lebesgue measure, $X : \Omega \rightarrow \mathbb{R}$ a random variable. Let $\mathcal{G}$ be the $\sigma$- algebra generated by n equally sized intervals in $[0,1]$.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    n = mo.ui.slider(1, 50, step = 1, label="n")
    n

    return (n,)


@app.cell
def _(n, np):

    boundaries = np.linspace(0, 1, n.value + 1)

    intervals = [
        f"({float(np.round(boundaries[b],3))}, {float(np.round(boundaries[b+1],3))}]"
        for b in range(len(boundaries)-1)
    ]

    intervals_latex = ", ".join(intervals)

    return boundaries, intervals_latex


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    $\mathcal{G} = \sigma \lbrace$
    """)
    return


@app.cell(hide_code=True)
def _(intervals_latex, mo):
    mo.md(f"""
    {intervals_latex}
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    $\rbrace$
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    Let's plot $X$ and the projection of $X$ onto $L^2(\Omega, \mathcal{G}, P)$
    """)
    return


@app.cell(hide_code=True)
def _(boundaries, np, plt):
    def X (x):
        return (x-0.75)*(x+0.2)*(x - 0.45)*(x-1.2) * 10 + 0.9

    interval_size = np.round(boundaries[1],3)

    x = np.linspace(0,1,1001)
    means = []
    for b in range(len(boundaries)-1):
        lower = boundaries[b]
        upper = boundaries[b+1]
        mean = np.mean(X(np.linspace(lower, upper)))

        plt.hlines(mean, lower, upper, color = "red")
    
        if b == 0:
            plt.hlines(mean, lower, upper, color = "red", label = r"$\mathbb{E}(X|\mathcal{G})$")
    



    plt.plot(x, X(x), label="X")
    plt.yticks([])
    plt.legend(loc = "upper left")


    return


if __name__ == "__main__":
    app.run()
